"""fix_mapper_error2

Revision ID: 80e08e34ec97
Revises: f65ebffac8d4
Create Date: 2024-11-21 15:41:05.866015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80e08e34ec97'
down_revision: Union[str, None] = 'f65ebffac8d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_subscription')
    op.add_column('orders', sa.Column('subscription_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'orders', 'subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'subscription_id')
    op.create_table('order_subscription',
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subscription_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_subscription_order_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name='order_subscription_subscription_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='order_subscription_pkey'),
    sa.UniqueConstraint('id', name='order_subscription_id_key')
    )
    # ### end Alembic commands ###
